version: '3.8'

services:
  chat-service-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-service-1
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_API_KEY=${KAFKA_API_KEY}
      - KAFKA_API_SECRET=${KAFKA_API_SECRET}
      - REDIS_ADDR=redis:6379
      - MONGO_URI=mongodb://mongo:27017
      - PORT=8080
      - SERVICE_INSTANCE_ID=instance-1
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  chat-service-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-service-2
    ports:
      - "8081:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_API_KEY=${KAFKA_API_KEY}
      - KAFKA_API_SECRET=${KAFKA_API_SECRET}
      - REDIS_ADDR=redis:6379
      - MONGO_URI=mongodb://mongo:27017
      - PORT=8080
      - SERVICE_INSTANCE_ID=instance-2
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: chat-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  mongo:
    image: mongo:5
    container_name: chat-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  redis-data:
  mongo-data: