version: '3.8'

services:
  chat-service-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-service-1
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_API_KEY=${KAFKA_API_KEY}
      - KAFKA_API_SECRET=${KAFKA_API_SECRET}
      - REDIS_HOST=redis-16702.c124.us-central1-1.gce.redns.redis-cloud.com
      - REDIS_PORT=16702
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=C9vQpbNP9YqVj1OeHmXTpCxlDKk4TxA0
      - MONGO_URI=mongodb+srv://sehej:Passw0rd942@wobitech.n7ilc.mongodb.net/wobichat-db?retryWrites=true&w=majority&appName=wobitech
      - PORT=8080
      - SERVICE_INSTANCE_ID=instance-1
    restart: unless-stopped

  chat-service-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-service-2
    ports:
      - "8081:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_API_KEY=${KAFKA_API_KEY}
      - KAFKA_API_SECRET=${KAFKA_API_SECRET}
      - REDIS_HOST=redis-16702.c124.us-central1-1.gce.redns.redis-cloud.com
      - REDIS_PORT=16702
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=C9vQpbNP9YqVj1OeHmXTpCxlDKk4TxA0
      - MONGO_URI=mongodb+srv://sehej:Passw0rd942@wobitech.n7ilc.mongodb.net/wobichat-db?retryWrites=true&w=majority&appName=wobitech
      - PORT=8080
      - SERVICE_INSTANCE_ID=instance-2
    restart: unless-stopped